excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://bvanelli.github.io
title: /dev/null
tagline: Nada para ver aqui
description: Um tutorial compreensivo de como falhar miseravelmente.
paginate: 10
