excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: https://bvanelli.github.io
title: /dev/null
tagline: Nada para ver aqui
description: Um tutorial compreensivo de como falhar miseravelmente.
paginate: 10
encoding: UTF-8
permalink: pretty
plugins: [jekyll-paginate]
